const lang = {
  en: {
    search: "Search",
    gptSearchPlaceholder: "What do you want to watch today?",
    gptSearch: "GPT Search",
    signOut: "Sign Out",
    nowPlaying: "Now Playing",
    popular: "Popular",
    topRated: "Top Rated",
    upcomingMovies: "Upcoming Movies",
    play: "Play",
    moreInfo: "More Info",
    home: "Home",
  },
  hindi: {
    search: "खोज",
    gptSearchPlaceholder: "आज आप क्या देखना चाहते हैं?",
    gptSearch: "जीपीटी खोज",
    signOut: "साइन आउट",
    nowPlaying: "अब दिखा रहे हैं",
    popular: "लोकप्रिय",
    topRated: "शीर्ष दर",
    upcomingMovies: "आने वाली फिल्में",
    play: "प्रारंभ",
    moreInfo: "और जानकारी",
    home: "होम",
  },
  spanish: {
    search: "Buscar",
    gptSearchPlaceholder: "¿Qué quieres ver hoy?",
    gptSearch: "Búsqueda GPT",
    signOut: "Desconectar",
    nowPlaying: "Jugando ahora",
    popular: "Popular",
    topRated: "Los más valorados",
    upcomingMovies: "Próximas películas",
    play: "Jugar",
    moreInfo: "Más información",
    home: "Hogar",
  },
};

export default lang;